# Third program
import pandas as pd
#import xlrd
df=pd.read_csv("empdata.csv" )
print(df)
print(df.index)# display index information (Total entries )DEFAULT INDEX
df1=df.set_index("empid")#creating new df1 having empid as index
print(df1)
df.set_index('empid',inplace=True)# set new index for original df 
#print(df)
print(df.loc[1004])
df.reset_index(inplace=True) # changing index back to original
print(df)                                #autogenerated


